name: my_workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout steps
              uses: actions/checkout@v4
            - name: job1
              run: echo "hello Nitin"

            - name: list files
              run: ls

            - name: read readme file
              run: cat README.md


